#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-grpcio_channelz
Version  : 1.45.0
Release  : 18
URL      : https://files.pythonhosted.org/packages/cb/8c/1fc3ab1ce336ee99982350e30b8b936058f21e9447e2027fd1d4e47265d3/grpcio-channelz-1.45.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/cb/8c/1fc3ab1ce336ee99982350e30b8b936058f21e9447e2027fd1d4e47265d3/grpcio-channelz-1.45.0.tar.gz
Summary  : Channel Level Live Debug Information Service for gRPC
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-grpcio_channelz-license = %{version}-%{release}
Requires: pypi-grpcio_channelz-python = %{version}-%{release}
Requires: pypi-grpcio_channelz-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(grpcio)
BuildRequires : pypi(protobuf)

%description
gRPC Python Channelz package
==============================
Channelz is a live debug tool in gRPC Python.

%package license
Summary: license components for the pypi-grpcio_channelz package.
Group: Default

%description license
license components for the pypi-grpcio_channelz package.


%package python
Summary: python components for the pypi-grpcio_channelz package.
Group: Default
Requires: pypi-grpcio_channelz-python3 = %{version}-%{release}

%description python
python components for the pypi-grpcio_channelz package.


%package python3
Summary: python3 components for the pypi-grpcio_channelz package.
Group: Default
Requires: python3-core
Provides: pypi(grpcio_channelz)
Requires: pypi(grpcio)
Requires: pypi(protobuf)

%description python3
python3 components for the pypi-grpcio_channelz package.


%prep
%setup -q -n grpcio-channelz-1.45.0
cd %{_builddir}/grpcio-channelz-1.45.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648148221
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-grpcio_channelz
cp %{_builddir}/grpcio-channelz-1.45.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-grpcio_channelz/34ac89724cb7e3fb36bcfe93efabfd012c569a0e
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-grpcio_channelz/34ac89724cb7e3fb36bcfe93efabfd012c569a0e

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
